### ISSUE TITLE
minecraft >1.13 bị lỗi texture 

### ISSUE THREAD

**Issue by dviet7427** [khanhduytran0/PojavLauncher#1]
![Screenshot_2021-07-11-12-32-00-74_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/87255856/125183983-93304600-e244-11eb-9b22-057db607a738.jpg)

**Comment by dviet7427** [comment]
![Uploading Screenshot_2021-07-11-12-31-44-62_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()

**Comment by dviet7427** [comment]
mong được chỉ ra lỗi và cách khắc phục

**Comment by khanhduytran0** [comment]
Đây không phải chỗ để report lỗi. Qua bên https://github.com/PojavLauncherTeam/PojavLauncher/isues :eyes:
