### ISSUE TITLE
Mod Installer

### ISSUE THREAD

**Issue by bruh-lol** [khanhduytran0/PojavLauncher#194]
I installed LabyMod and it wouldn't show up in the version menu, this is on v3.0.1 preview 2.

**Comment by khanhduytran0** [comment]
This v3.0.1 is still on error so nothing will work.

**Comment by bruh-lol** [comment]
Okay!

**Comment by khanhduytran0** [comment]
I fixed OpenJDK, that error cause anything to not work.

**Comment by khanhduytran0** [comment]
> I fixed OpenJDK, that error cause anything to not work.

But still not on new devices.
